### ISSUE TITLE
Authentication Issue React->Django

### ISSUE THREAD

**Issue by camdenkr** [BostonUniversitySeniorDesign/21-11-stod#13]
**Following error occurs on every page load:**

Traceback (most recent call last):
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/Users/camdenkronhaus/21-11-stod/stod-backend/env/lib/python3.9/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'drf_pretty_exception_handler'

**Comment by sharithg** [comment]
pip install -r requirements.txt 

I installed drf_pretty_exception_handler to handle exceptions
