### ISSUE TITLE
Groups Warning

### ISSUE THREAD

**Issue by camdenkr** [BostonUniversitySeniorDesign/21-11-stod#14]
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Groups`. See https://reactjs.org/link/warning-keys for more information.
    at Group (http://localhost:3000/static/js/main.chunk.js:2168:74)
    at Groups (http://localhost:3000/static/js/main.chunk.js:2325:74)
    at Route (http://localhost:3000/static/js/0.chunk.js:87696:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:87898:29)
    at div
    at Router (http://localhost:3000/static/js/0.chunk.js:87331:30)
    at BrowserRouter (http://localhost:3000/static/js/0.chunk.js:86951:35)
    at Provider (http://localhost:3000/static/js/0.chunk.js:84567:20)
    at App (http://localhost:3000/static/js/main.chunk.js:42:58)

**Comment by sharithg** [comment]
.map((val, index) => {
    < Item key={index}  />
}

Anything being used in .map should have a unique key which is index in this case
